apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders
  namespace: kafka
  labels:
    strimzi.io/cluster: test-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 604800000
